SELECT *,
    (TECH_TOOL_EXPENSE+HR_EXPENSE+WAREHOUSE_EXPENSE+OTHER_EXPENSE+REFUND_COST+SALARY) as TOTAL_COST,
    REVENUE-(TECH_TOOL_EXPENSE+HR_EXPENSE+WAREHOUSE_EXPENSE+OTHER_EXPENSE+REFUND_COST+SALARY) as PROFIT
FROM {{ ref('int_daily_finance') }}