SELECT
    IP,
    OS, 
    CAST(CLIENT_ID AS STRING) AS CLIENT_ID,
    SESSION_AT AS SESSION_AT_TS,
    SESSION_ID,
    _FIVETRAN_DELETED,
    _FIVETRAN_ID,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('snowflake','sessions')}}