SELECT
    CLIENT_NAME, 
    ORDER_ID,
    ORDER_AT AS ORDER_AT_TS,
    PAYMENT_INFO,
    PAYMENT_METHOD,
    PHONE,
    SESSION_ID,
    SHIPPING_ADDRESS,
    CAST(SUBSTR(SHIPPING_COST,4) AS INT) AS ORDERS,
    STATE,
    TAX_RATE,
    _FIVETRAN_DELETED,
    _FIVETRAN_ID,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('snowflake','orders')}}